# Generated by Django 4.2.8 on 2024-01-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmdash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='category',
            field=models.CharField(choices=[('Tr', 'Trigonometric'), ('Ln', 'Linear'), ('Log', 'Logarithmic')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
