# Generated by Django 4.2.8 on 2024-01-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmdash', '0003_alter_dashboard_options_alter_dashboard_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ['title', 'status'],
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pmdash.tag'),
        ),
    ]
